### ISSUE TITLE
dist/ and yarn.lock

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid-js#1]
I had to create the dist/ dir and also remove the yarn.lock file to make yarn work. Also added `always-auth=true` to ~/.npmrc because of https://github.com/yarnpkg/yarn/issues/3093, but not sure if that is needed.

**Comment by Ramblurr** [comment]
Could you paste the errors you got with yarn before you added the `always-auth=true`? Did you create an npm account, that's kinda weird. It should just work without an account.

Also we should add back the yarn.lock file too, because even though it is generated it is meant to be committed. The lock file locks dependencies (and sub dependencies) to specific versions, so that it is guaranteed we are all using the exact same dependency tree. Without that we could end up with slightly different tree of deps that could cause strange behavior or break the app entirely.

Lets try and resolve the errors you had with `always-auth=true` and the lock file.

**Comment by gauteh** [comment]
Actually, the 'always-auth=true' wasn't what solved it for me, just 
removing `yarn.lock` did:

```bash

[strange astroid-js](master) $ yarn
yarn install v1.1.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://nexus.private/repository/npm/abbrev/-/abbrev-1.1.0.tgz: Request failed "401 Unauthorized"
error An unexpected error occurred: "https://nexus.private/repository/npm/caniuse-lite/-/caniuse-lite-1.0.30000738.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/gaute/dev/mail/notm/astroid-js/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by Ramblurr** [comment]
Ah of course! Will make sure thats fixed when I push this to the main repo
